{
 "title": "JMeter",
 "description": "A grafana dashboard to inspect jmeter metrics via prometheus exporter",
 "tags": [ "jmeter" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,10m" },
   { "name": "kafka_container", "query": "${VAR_KAFKA_CONTAINER}" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "singlestat",
   "description": "Total Requests",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(jsr223_rt_as_summary_count)"
    }
   ]
  },
  {
   "title": "Success",
   "type": "singlestat",
   "description": "Total Success Requests",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(jsr223_rt_as_summary_count{code=\"200\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "description": "Total Failed Requests",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jsr223_rt_as_summary_count{code!=\"200\"}"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(avg(rate(jsr223_rt_as_summary_count{code!=\"200\"}[$interval]))/avg(rate(jsr223_rt_as_summary_count[$interval])))"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "singlestat",
   "description": "Average Response Time in ms",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(jsr223_rt_as_summary_sum[$interval])/rate(jsr223_rt_as_summary_count[$interval])",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "singlestat",
   "description": "Total Active Users",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Requests vs OK/KO (per second)",
   "type": "graph",
   "description": "Requests vs requests that's OK/OK (per second)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jsr223_rt_as_summary_count{code=\"200\"}[$interval])) by (label)",
     "legendFormat": "OK ({{label}})"
    },
    {
     "expr": "sum(rate(jsr223_rt_as_summary_count{code!=\"200\"}[$interval])) by (label)",
     "legendFormat": "KO ({{label}})"
    },
    {
     "expr": "sum(rate(jsr223_rt_as_summary_count[$interval])) by (label)",
     "legendFormat": "Total Requests per second ({{label}})"
    }
   ]
  },
  {
   "title": "Avg. Response Time vs OK/KO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jsr223_rt_as_summary_sum[$interval])) by (label)",
     "legendFormat": "Avg Response Time ({{label}})"
    },
    {
     "expr": "sum(rate(jsr223_rt_as_summary_sum{code=\"200\"}[$interval]))  by (label)",
     "legendFormat": "OK ({{label}})"
    },
    {
     "expr": "sum(rate(jsr223_rt_as_summary_sum{code!=\"200\"}[$interval])) by (label)",
     "legendFormat": "KO ({{label}})"
    }
   ]
  },
  {
   "title": "Virtual Users vs OK/KO",
   "type": "graph",
   "description": "Virtual Users (Threads) vs OK/KO",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})",
     "legendFormat": "Virtual Users"
    },
    {
     "expr": "sum(rate(jsr223_rt_as_summary_count{code=\"200\"}[$interval]))",
     "legendFormat": "Request OK per second"
    },
    {
     "expr": "sum(rate(jsr223_rt_as_summary_count{code!=\"200\"}[$interval]))",
     "legendFormat": "Request KO per second"
    }
   ]
  },
  {
   "title": "Avg. Response Time vs Virtual Users",
   "type": "graph",
   "description": "Average response time for success requests vs virtal users",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jsr223_rt_as_summary_sum{code=\"200\"}[$interval]))",
     "legendFormat": "Avg Response Time"
    },
    {
     "expr": "sum(jmeter_threads{state=\"active\"})",
     "legendFormat": "Virtual Users"
    }
   ]
  },
  { "title": "Response times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Pct response times",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(jsr223_rt_as_summary{code=\"200\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC % time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{container=\"$kafka_container\"}[$interval])",
       "legendFormat": "{{container}} - {{gc}} "
      }
     ]
    },
    {
     "title": "JVM heap  - free memory by pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(jvm_memory_pool_bytes_committed {container=\"$kafka_container\"}) - (jvm_memory_pool_bytes_used{container=\"$kafka_container\"}) ",
       "legendFormat": "{{container}} - {{pool}}"
      }
     ]
    },
    {
     "title": "JVM heap -  used memory by pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(jvm_memory_pool_bytes_used{container=\"$kafka_container\"}) ",
       "legendFormat": "{{container}} - {{pool}}"
      }
     ]
    },
    {
     "title": "JVM free memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "((jvm_memory_bytes_max {container=\"$kafka_container\"}) - (jvm_memory_bytes_used{container=\"$kafka_container\"}))",
       "legendFormat": "{{container}} - {{area}}"
      }
     ]
    }
   ]
  }
 ]
}