{
 "title": "Kafka Performance",
 "description": "Created for running Kafka locally (or I would say none OpenShift environment)",
 "tags": [ "Kafka" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "kafka_broker",
    "label": "Broker",
    "query": {
     "query": "query_result(kafka_cluster_partition_replicascount)"
    }
   },
   {
    "name": "kafka_topic",
    "label": "Topic",
    "query": {
     "query": "query_result(kafka_cluster_partition_replicascount{instance=~\"$kafka_broker.*\"})"
    }
   },
   {
    "name": "kafka_partition",
    "label": "Partition",
    "query": {
     "query": "query_result(kafka_cluster_partition_replicascount{instance=~\"$kafka_broker.*\", topic=~\"$kafka_topic.*\"})"
    }
   },
   { "name": "kafka_job", "query": "${VAR_KAFKA_JOB}" },
   { "name": "zookeeper_job", "query": "${VAR_ZOOKEEPER_JOB}" }
  ]
 },
 "panels": [
  { "title": "Kafka Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Broker Active Controller",
   "type": "singlestat",
   "description": "Number of Broker Active Controller",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{instance=~\"$kafka_broker.*\", job=\"$kafka_job\"})"
    }
   ]
  },
  {
   "title": "ISR",
   "type": "singlestat",
   "description": "Total In-sync Replicas Count",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_insyncreplicascount{instance=~\"$kafka_broker.*\", topic=~\"$kafka_topic.*\", partition=~\"$kafka_partition\", job=\"$kafka_job\"})"
    }
   ]
  },
  {
   "title": "Replica",
   "type": "singlestat",
   "description": "Total Replica count for partitions.",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_replicascount{instance=~\"$kafka_broker.*\", topic=~\"$kafka_topic.*\", partition=~\"$kafka_partition.*\", job=\"$kafka_job\"})"
    }
   ]
  },
  {
   "title": "Incoming Messages Rate",
   "type": "singlestat",
   "description": "Incoming Messages Rate",
   "gridPos": { "h": 2, "w": 6, "x": 9, "y": 1 },
   "format": "wps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{instance=~\"$kafka_broker.*\",topic=~\"$kafka_topic.*\", job=\"$kafka_job\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Incoming Byte Rate",
   "type": "singlestat",
   "description": "Total Incoming Byte Rate",
   "gridPos": { "h": 2, "w": 6, "x": 15, "y": 1 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{instance=~\"$kafka_broker.*\",topic=~\"$kafka_topic.*\", job=\"$kafka_job\"}[1m]))"
    }
   ]
  },
  {
   "title": "Partitions under mininimum ISR",
   "type": "singlestat",
   "description": "Number of partitions which are under their minimum in sync replica count (| ISR | < | min.insync.replicas |).",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{instance=~\"$kafka_broker.*\",topic=~\"$kafka_topic.*\", partition=~\"$kafka_partition\", job=\"$kafka_job\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underreplicated{instance=~\"$kafka_broker\",topic=~\"$kafka_topic\", job=\"$kafka_job\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "singlestat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{instance=~\"$kafka_broker\", job=\"$kafka_job\"})"
    }
   ]
  },
  {
   "title": "Online Replicas",
   "type": "singlestat",
   "description": "Replicas that are online",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{instance=~\"$kafka_broker.*\", job=\"$kafka_job\"})"
    }
   ]
  },
  {
   "title": "Total Outgoing Byte Rate",
   "type": "singlestat",
   "description": "Total Outgoing Byte Rate",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesout_total{instance=~\"$kafka_broker.*\", job=\"$kafka_job\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Produce Request Rate",
   "type": "singlestat",
   "description": "Total Produce Request Rate",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalproducerequests_total{instance=~\"$kafka_broker.*\", job=\"$kafka_job\"}[1m]))"
    }
   ]
  },
  { "title": "Performance Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Broker CPU Usage",
   "type": "graph",
   "description": "Aggregated Kafka Broker CPU Usage",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$kafka_broker\",job=\"$kafka_job\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Broker JVM Memory Usage",
   "type": "graph",
   "description": "Kafka Broker JVM Memory Usage",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=~\"$kafka_broker\",job=\"$kafka_job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Broker Produce Req. Rate",
   "type": "graph",
   "description": "Produce Request Rate.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalproducerequests_total{instance=~\"$kafka_broker\",topic=~\"$kafka_topic\", job=\"$kafka_job\"}[1m]))",
     "legendFormat": "Total Produce Request Rate"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{instance=\"$kafka_broker\",topic=~\"$kafka_topic\", job=\"$kafka_job\"}[1m]))",
     "legendFormat": "Failed Produce Request Rate"
    }
   ]
  },
  {
   "title": "Broker Fetch Req. Rate",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{instance=~\"$kafka_broker\",topic=~\"$kafka_topic\", job=\"$kafka_job\"}[1m]))",
     "legendFormat": "Fetch Request Rate"
    },
    {
     "expr": "  sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{instance=\"$kafka_broker\",topic=~\"$kafka_topic\", job=\"$kafka_job\"}[1m]))",
     "legendFormat": "Failed Fetch Request Rate"
    }
   ]
  },
  {
   "title": "Zookeeper Memory Usage",
   "type": "graph",
   "description": "ZooKeeper Pods Memory Usage",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{job=\"$zookeeper_job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Zookeeper CPU Usage",
   "type": "graph",
   "description": "Aggregated ZooKeeper Pods CPU Usage",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"$zookeeper_job\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Broker Msg In Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{instance=~\"$kafka_broker\",topic=~\"$kafka_topic\", job=\"$kafka_job\"}[1m]))",
     "legendFormat": "Total Incoming Messages Rate"
    }
   ]
  },
  {
   "title": "Broker Byte Rate",
   "type": "graph",
   "description": "Byte Rate",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{instance=~\"$kafka_broker\",topic=~\"$kafka_topic\", job=\"$kafka_job\"}[1m]))",
     "legendFormat": "Total Incoming Byte Rate"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesout_total{instance=\"$kafka_broker\",topic=~\"$kafka_topic\", job=\"$kafka_job\"}[1m]))",
     "legendFormat": "Total Outgoing Byte Rate"
    }
   ]
  },
  {
   "title": "Broker Under Replicated Partition",
   "type": "graph",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{instance=~\"$kafka_broker\", job=\"$kafka_job\"})",
     "legendFormat": "Partition Count"
    }
   ]
  },
  {
   "title": "Broker Partitions under Minimum ISR",
   "type": "graph",
   "description": "Number of partitions which are under their minimum in sync replica count (| ISR | == | min.insync.replicas |).",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{instance=~\"$kafka_broker\", topic=~\"$kafka_topic\", job=\"$kafka_job\"})",
     "legendFormat": "Partition Count"
    }
   ]
  },
  { "title": "Other Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Zookeeper JVM Memory Used",
   "type": "graph",
   "description": "JVM Memory Used",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{job=\"$zookeeper_job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Broker JVM GC Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{instance=~\"$kafka_broker\", job=\"$kafka_job\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Broker JVM GC Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_count{instance=~\"$kafka_broker\", job=\"$kafka_job\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Broker Open File Descriptors",
   "type": "graph",
   "description": "Open File Descriptors",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$kafka_broker\", job=\"$kafka_job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Broker Network Processor Avg Idle Percent",
   "type": "graph",
   "description": "Broker Network Processor Avg Idle Percent",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kafka_network_socketserver_networkprocessoravgidlepercent{instance=~\"$kafka_broker\", job=\"$kafka_job\"}*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Broker Log Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{instance=~\"$kafka_broker\",topic=~\"$kafka_topic\",partition=~\"$kafka_partition\",job=\"$kafka_job\"}) by (topic,partition)",
     "legendFormat": "{{topic}}:{{partition}}"
    }
   ]
  },
  {
   "title": "Broker JVM Thread Count",
   "type": "graph",
   "description": "Broker JVM Thread Count",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$kafka_broker\",job=\"$kafka_job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}