{
 "title": "JMeter",
 "description": "A grafana dashboard to inspect jmeter metrics via prometheus exporter",
 "tags": [ "jmeter" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "Total Requests",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jsr223_rt_as_summary_count)"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "description": "Total success requests",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jsr223_rt_as_summary_count{code=\"200\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "description": "Total Failed Requests",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jsr223_rt_as_summary_count{code!=\"200\"}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "description": "Total Active Users",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "description": "Average Response Time in ms",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((rate(jsr223_rt_as_summary_sum[$interval])/(rate(jsr223_rt_as_summary_count[$interval])>0)))",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "description": "Total Requests per second",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(jsr223_rt_as_summary_count[$interval])",
     "legendFormat": "Request per second"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "description": "OK requests per second",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(jsr223_rt_as_summary_count{code=\"200\"}[$interval])"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "stat",
   "description": "KO requests per second",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(jsr223_rt_as_summary_count{code!=\"200\"}[$interval])"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"jmeter\"}[$interval])"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{job=\"jmeter\"})"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Virtual Users vs OK/KO",
   "type": "graph",
   "description": "Virtual Users (Threads) vs OK/KO",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "jmeter_threads{state=\"active\"}",
     "legendFormat": "Virtual Users"
    },
    {
     "expr": "rate(jsr223_rt_as_summary_count{code=\"200\"}[$interval])",
     "legendFormat": "Request OK per second"
    },
    {
     "expr": "rate(jsr223_rt_as_summary_count{code!=\"200\"}[$interval])",
     "legendFormat": "Request KO per second"
    }
   ]
  },
  {
   "title": "Total Requests vs OK/KO",
   "type": "graph",
   "description": "Total requests(per second) vs requests that's OK/OK(per second)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jsr223_rt_as_summary_count{code=\"200\"}[$interval])",
     "legendFormat": "OK"
    },
    {
     "expr": "rate(jsr223_rt_as_summary_count{code!=\"200\"}[$interval])",
     "legendFormat": "KO"
    },
    {
     "expr": "rate(jsr223_rt_as_summary_count[$interval])",
     "legendFormat": "Total Requests per second"
    }
   ]
  },
  {
   "title": "Avg. Response Time vs Virtual Users",
   "type": "graph",
   "description": "Average response time for success requests vs virtal users",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg((rate(jsr223_rt_as_summary_sum[$interval])/(rate(jsr223_rt_as_summary_count[$interval])>0)))",
     "legendFormat": "Avg Response Time"
    },
    {
     "expr": "jmeter_threads{state=\"active\"}",
     "legendFormat": "Virtual Users"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(jsr223_rt_as_summary_count[$interval])"
    }
   ]
  },
  { "title": "Response times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Avg. response time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": " avg (rate(jsr223_rt_as_summary_sum[$interval]) / (rate(jsr223_rt_as_summary_count[$interval])>0)) by (label)",
     "legendFormat": "{{label}} "
    }
   ]
  },
  {
   "title": "Pct response times",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(jsr223_rt_as_summary{code=\"200\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Requests per second", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jsr223_rt_as_summary_count{code=\"200\"}[$interval])",
     "legendFormat": "OK ({{label}})"
    },
    {
     "expr": "rate(jsr223_rt_as_summary_count{code!=\"200\"}[$interval])",
     "legendFormat": "KO ({{label}})"
    }
   ]
  },
  {
   "title": "by label",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jsr223_rt_as_summary_count{code=\"200\"}[$interval]) ",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "by HTTP code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jsr223_rt_as_summary_count [$interval]) ",
     "legendFormat": "HTTP {{code}} ({{label}})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "by HTTP code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(code) (rate(jsr223_rt_as_summary_count{code!=\"200\"}[$interval]))",
       "legendFormat": "HTTP {{code}}"
      }
     ]
    },
    {
     "title": "by label",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (label) (rate(jsr223_rt_as_summary_count{code!=\"200\"}[$interval]))",
       "legendFormat": "{{label}}"
      }
     ]
    }
   ]
  },
  { "title": "Test farm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "GC % time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"jmeter\"}[1m])",
     "legendFormat": "{{instance}} - {{gc}} "
    }
   ]
  },
  {
   "title": "JVM heap  - free memory by pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(jvm_memory_pool_bytes_committed {job=~\"jmeter\"}) - (jvm_memory_pool_bytes_used{job=~\"jmeter\"}) ",
     "legendFormat": "{{instance}} - {{pool}}"
    }
   ]
  },
  {
   "title": "JVM heap -  used memory by pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(jvm_memory_pool_bytes_used{job=\"jmeter\"}) ",
     "legendFormat": "{{instance}} - {{pool}}"
    }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(jvm_memory_bytes_max {job=\"jmeter\"}) - (jvm_memory_bytes_used{job=\"jmeter\"})",
     "legendFormat": "{{instance}} - {{area}}"
    }
   ]
  }
 ]
}